package ch08;

import java.util.concurrent.ExecutionException;

public class MainTest1 {
	//메인 함수
	public static void main(String[] args) {

		
//		// 문법 확인
//		try {
//			// 예외가 발생할 수 있는 코드를 작성 한다
//		}catch(FileNotFoundException e) {
//			// 예외가 발생하면 동작 하는 코드
//		}catch(Exception e1) {
//			
//		}
		
		
		
	}// end of main

}// end of class
